### ISSUE TITLE
Error: unable to determine plugin type

### ISSUE THREAD

**Issue by jnbdz** [hashicorp/vault-auth-plugin-example#15]
Hi, 

I am getting this error: 

```
Error writing data to sys/plugins/catalog/example-auth-plugin: Error making API request.

URL: PUT http://127.0.0.1:1234/v1/sys/plugins/catalog/example-auth-plugin
Code: 500. Errors:

* 1 error occurred:
        * unable to determine plugin type
```

After running this command:
```
# vault write sys/plugins/catalog/example-auth-plugin \
>     sha_256="${SHA256}" \
>     command="vault-auth-plugin-example"
```

I am running everything in a container.

```
podman run \
        --rm \
        --cap-add=IPC_LOCK \
        -p '8200:8200' \
        -e 'VAULT_ADDR=127.0.0.1:1234' \
        -e 'VAULT_DEV_LISTEN_ADDRESS=127.0.0.1:1234' \
        -v './data/:/var/lib/vault' \
        -v './code/vault-auth-plugin-example:/etc/vault/plugins/vault-auth-plugin-example' \
        -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "log_level": "debug", "disable_mlock": true, "listener": [{"tcp": {"tls_disable": true}}], "plugin_directory": "/etc/vault/plugins/", "default_lease_ttl": "168h", "max_lease_ttl": "720h"}' \
        --name=dev-pam-vault \
        vaultplugin
```

Vault version: Vault v1.3.0

I did run this command first: 
`export SHA256=$(shasum -a 256 "/etc/vault/plugins/vault-auth-plugin-example" | cut -d' ' -f1)`

I also tried: 

```
# vault write sys/plugins/catalog/example-auth-plugin \
>     sha_256="${SHA256}" \
>     command="vault-auth-plugin-example"
```

But then I get this error: 

```
Error writing data to sys/plugin/catalog/example-auth-plugin: Error making API request.

URL: PUT http://127.0.0.1:1234/v1/sys/plugin/catalog/example-auth-plugin
Code: 404. Errors:

* 1 error occurred:
        * unsupported path
```

Any ideas?

Thank you in advance.

**Comment by jnbdz** [comment]
Hi @pierreavn, 
No I have not.
I haven't looked into it since than.

Sorry :(

**Comment by EmmEff** [comment]
FWIW, it appears the path should be `sys/plugins/catalog/auth/example-auth-plugin`. Hope this helps somebody :)

**Comment by tomhjp** [comment]
Sorry this went unanswered for so long. @EmmEff makes a good point, it would be better if the readme gave the path that specified the type `auth/` in the path. I'd also recommend using the bespoke `vault` command for it:

```
vault plugin register \
    -sha256="${SHA256}" \
    -command="vault-auth-plugin-example" \
    auth example-auth-plugin
```

I've updated the readme and run through it again, and it works locally, so I'm afraid I'm unable to repro currently.

I think there was probably a different underlying error, because if all is working well, Vault should be able to automatically work out the plugin type by running it and calling the `Type()` gRPC method. Perhaps the binary was for the wrong OS/arch combination or something. The code in question has been updated considerably since 1.3.0, and should give more details if anyone can still repro. There should also be more details in the Vault server logs, especially debug logs.

Happy to help debug if there's anyone still following this issue, but I'll close for now.
