### ISSUE TITLE
Incompatible API version with plugin. Plugin version: 2, Client versions: [3 4]

### ISSUE THREAD

**Issue by maxiscoding28** [hashicorp/vault-auth-plugin-example#19]
Hey @tomhjp, thanks for the demo code. Trying to get it set up on an amazon ec2 instance and I'm hitting the following error. Any ideas on what I need to do in order to fix it?

```
ec2-user@i-0e4d6c0e23197e43a ~> vault version
Vault v1.12.1+ent (d5c023cac2ecfb691b92082696e4b256dbab4a84), built 2022-10-28T12:10:32Z
ec2-user@i-0e4d6c0e23197e43a ~> vault plugin list | grep example
example-auth-plugin                  auth        n/a
ec2-user@i-0e4d6c0e23197e43a ~> vault auth enable -path=example -plugin-name=example-auth-plugin plugin
Error enabling example-auth-plugin auth: Error making API request.

URL: POST http://ec2-34-220-9-8.us-west-2.compute.amazonaws.com:8200/v1/sys/auth/example
Code: 400. Errors:

* invalid backend version: 2 errors occurred:
	* Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
	* Incompatible API version with plugin. Plugin version: 2, Client versions: [4 3]
```

**Comment by tomhjp** [comment]
Thanks for reporting. I opened #20, thinking this must be because the `sdk` package is out of date (where the protocol versions for the plugin are specified, 2 is old, 3 and 4 are current). However, on a closer look, the current code is fine, but we just haven't done a release in a while. You should be able to fix this by building the plugin yourself (fully worked example in docker-test.sh), but I'll try and get a v0.2.0 released soon as well.
